### ISSUE TITLE
Error Can't Open Camera android app

### ISSUE THREAD

**Issue by aucifer16** [vidinoti/cordova-plugin-PixLive#8]
My Log It Error About
    Process: com.mycompany.myArKai, PID: 6765
                                                                     java.lang.IllegalArgumentException: eglChooseConfig failed
                                                                         at com.vidinoti.android.vdarsdk.VDARAnnotationView$VDARInternalAnnotationView$BaseConfigChooser.chooseConfig(VDARAnnotationView.java:1522)
                                                                         at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1042)
                                                                         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1412)
                                                                         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
10-30 07:35:57.215 2142-3228/system_process W/ActivityManager:   Force finishing activity 

Full Log

30 07:35:56.724 1479-1907/? V/EmulatedCamera_BaseCamera: getCameraInfo
                                                            
                                                            [ 10-30 07:35:56.767  6765: 6765 I/VDARInternalAnnotationView com.vidinoti.android.vdarsdk.VDARAnnotationView$VDARInternalAnnotonAttachedToWindow called
                                                            
                                                            [ 10-30 07:35:56.768  6765: 6765 I/VDARInternalAnnotationView com.vidinoti.android.vdarsdk.VDARAnnotationView$VDARInternalAnnotonResume annotview
10-30 07:35:56.856 6765-6776/com.mycompany.myArKai I/art: Background partial concurrent mark sweep GC freed 1716(103KB) AllocSpace objects, 3(21MB) LOS objects, 25% free, 11MB/15MB, paused 10.743ms total 231.465ms
                                                          
                                                          [ 10-30 07:35:56.857  6765: 6835 I/VDARInternalAnnotationView com.vidinoti.android.vdarsdk.VDARAnnotationView$VDARInternalAnnotStarting rendering
10-30 07:35:56.858 6765-6765/com.mycompany.myArKai V/Android5Camera: startImageStream
10-30 07:35:56.964 6765-6808/com.mycompany.myArKai D/EGL_emulation: eglMakeCurrent: 0xcf265920: ver 2 0 (tinfo 0xcdeaf8e0)
                                                                    
                                                                    [ 10-30 07:35:57.142  6765: 6835 D/         ]
                                                                    HostConnection::get() New Host Connection established 0xc82ae280, tid 6835
10-30 07:35:57.142 2142-2209/system_process W/art: Long monitor contention with owner Binder:2142_E (4570) at int com.android.server.wm.WindowManagerService.relayoutWindow(com.android.server.wm.Session, android.view.IWindow, int, android.view.WindowManager$LayoutParams, int, int, int, int, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.content.res.Configuration, android.view.Surface)(WindowManagerService.java:2850) waiters=0 in void com.android.server.wm.WindowAnimator$1.doFrame(long) for 147ms
10-30 07:35:57.144 6765-6835/com.mycompany.myArKai E/AndroidRuntime: FATAL EXCEPTION: GLThread 119
                                                                     Process: com.mycompany.myArKai, PID: 6765
                                                                     java.lang.IllegalArgumentException: eglChooseConfig failed
                                                                         at com.vidinoti.android.vdarsdk.VDARAnnotationView$VDARInternalAnnotationView$BaseConfigChooser.chooseConfig(VDARAnnotationView.java:1522)
                                                                         at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1042)
                                                                         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1412)
                                                                         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
10-30 07:35:57.215 2142-3228/system_process W/ActivityManager:   Force finishing activity com.mycompany.myArKai/.MainActivity
10-30 07:35:57.270 6765-6776/com.mycompany.myArKai I/art: Background sticky concurrent mark sweep GC freed 232(23KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 18MB/18MB, paused 18.094ms total 100.865ms
10-30 07:35:57.299 6765-6765/com.mycompany.myArKai W/art: Attempt to remove non-JNI local reference, dumping thread
10-30 07:35:57.301 6765-6808/com.mycompany.myArKai D/EGL_emulation: eglMakeCurrent: 0xcf265920: ver 2 0 (tinfo 0xcdeaf8e0)
10-30 07:35:57.451 6765-6776/com.mycompany.myArKai W/art: Suspending all threads took: 19.029ms
10-30 07:35:57.532 6765-6765/com.mycompany.myArKai I/Choreographer: Skipped 39 frames!  The application may be doing too much work on its main thread.
10-30 07:35:57.546 6765-6776/com.mycompany.myArKai I/art: Background partial concurrent mark sweep GC freed 259(28KB) AllocSpace objects, 1(7MB) LOS objects, 25% free, 11MB/15MB, paused 28.915ms total 222.257ms
10-30 07:35:57.720 2142-4887/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
10-30 07:35:57.721 2142-4887/system_process D/OpenGLRenderer: Swap behavior 1
10-30 07:35:57.722 2142-4887/system_process W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
10-30 07:35:57.723 2142-4887/system_process D/OpenGLRenderer: Swap behavior 0
10-30 07:35:57.741 2142-4887/system_process D/EGL_emulation: eglCreateContext: 0x7ce175471a00: maj 2 min 0 rcv 2
10-30 07:35:57.796 2142-4887/system_process D/EGL_emulation: eglMakeCurrent: 0x7ce175471a00: ver 2 0 (tinfo 0x7ce179f19c80)
10-30 07:35:57.818 2142-2186/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{fa79ee8 u0 com.mycompany.myArKai/.MainActivity t241 f}
10-30 07:35:57.821 6765-6765/com.mycompany.myArKai I/VDARSDKController: onActivityPaused
10-30 07:35:57.866 6765-6765/com.mycompany.myArKai D/CordovaActivity: Paused the activity.
                                                                      
                                                                      [ 10-30 07:35:57.866  6765: 6765 I/VDARInternalAnnotationView com.vidinoti.android.vdarsdk.VDARAnnotationView$VDARInternalAnnotonPause AnnotationView
10-30 07:35:57.867 6765-6765/com.mycompany.myArKai V/Android5Camera: stopImageStream
10-30 07:35:57.926 2142-4887/system_process D/EGL_emulation: eglMakeCurrent: 0x7ce175471a00: ver 2 0 (tinfo 0x7ce179f19c80)
10-30 07:35:58.099 6765-6820/com.mycompany.myArKai I/App: WARNING: Back Button Default Behavior will be overridden.  The backbutton event will be fired!
10-30 07:35:58.107 3396-3523/com.google.android.googlequicksearchbox:search D/EGL_emulation: eglMakeCurrent: 0xe0175c40: ver 2 0 (tinfo 0xdff03f80)
10-30 07:35:58.117 1310-2989/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 2695168
                                                 
                                                 
                                                 [ 10-30 07:35:58.194  2142: 2186 D/         ]
                                                 HostConnection::get() New Host Connection established 0x7ce171a4d040, tid 2186
10-30 07:35:58.230 1310-1310/? E/EGL_emulation: tid 1310: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
10-30 07:35:58.320 2142-2209/system_process W/art: Long monitor contention with owner ActivityManager (2186) at android.graphics.Bitmap com.android.server.wm.WindowManagerService.screenshotApplicationsInner(android.os.IBinder, int, int, int, boolean, float, android.graphics.Bitmap$Config, boolean)(WindowManagerService.java:6462) waiters=0 in void com.android.server.wm.WindowManagerService$H.handleMessage(android.os.Message) for 327ms
10-30 07:35:58.367 2142-2161/system_process W/art: Long monitor contention with owner ActivityManager (2186) at void com.android.server.am.ActivityStack$ActivityStackHandler.handleMessage(android.os.Message)(ActivityStack.java:373) waiters=0 in int com.android.server.am.ActivityManagerService.bindService(android.app.IApplicationThread, android.os.IBinder, android.content.Intent, java.lang.String, android.app.IServiceConnection, int, java.lang.String, int) for 371ms
10-30 07:35:58.381 2142-4286/system_process W/art: Long monitor contention with owner ActivityManager (2186) at void com.android.server.am.ActivityStack$ActivityStackHandler.handleMessage(android.os.Message)(ActivityStack.java:373) waiters=1 in void com.android.server.am.ActivityManagerService.activityPaused(android.os.IBinder) for 347ms
10-30 07:35:58.514 2142-2187/system_process I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
10-30 07:35:58.521 6765-6765/com.mycompany.myArKai I/Choreographer: Skipped 57 frames!  The application may be doing too much work on its main thread

help me please

**Comment by aucifer16** [comment]
OK it work I can test my application from real device not test from Emulator
